// Seed data for initial games in Firestore
// Used by Admin panel to populate the games collection

export const SEED_GAMES = [
  {
    gameId: "game_001",
    gameName: "Stellar Nexus",
    platform: "PS5",
    genre: "Action RPG",
    description: "An epic space action RPG set in a dying universe. Command a team of heroes to save humanity from an alien threat.",
    coverImageUrl: "/games/stellar_nexus.png",
    releaseDate: "2025-12-01",
    rating: 4.8,
    totalRatings: 1240,
    totalPlays: 3850,
    isNewArrival: true,
    isTopRated: true,
    isMostPlayed: false,
    avgSessionDuration: 2,
    status: "active",
    createdAt: new Date().toISOString(),
  },
  {
    gameId: "game_002",
    gameName: "Shadow Realm",
    platform: "Xbox Series X",
    genre: "Dark Fantasy",
    description: "Battle ancient demons in a cursed realm. Master dark magic and forge legendary weapons to survive.",
    coverImageUrl: "/games/shadow_realm.png",
    releaseDate: "2025-10-15",
    rating: 4.6,
    totalRatings: 980,
    totalPlays: 4200,
    isNewArrival: false,
    isTopRated: true,
    isMostPlayed: true,
    avgSessionDuration: 2,
    status: "active",
    createdAt: new Date().toISOString(),
  },
  {
    gameId: "game_003",
    gameName: "Turbo Circuit",
    platform: "PS5",
    genre: "Racing",
    description: "Compete in futuristic hover-car races across 30 neon-lit tracks. Customize your ride and dominate the circuit.",
    coverImageUrl: "/games/turbo_circuit.png",
    releaseDate: "2026-01-20",
    rating: 4.3,
    totalRatings: 640,
    totalPlays: 5600,
    isNewArrival: true,
    isTopRated: false,
    isMostPlayed: true,
    avgSessionDuration: 2,
    status: "active",
    createdAt: new Date().toISOString(),
  },
  {
    gameId: "game_004",
    gameName: "Jungle Strike",
    platform: "Xbox Series X",
    genre: "Tactical Shooter",
    description: "Lead elite special forces through 20 intense jungle missions. Use strategy, stealth, and firepower to complete objectives.",
    coverImageUrl: "/games/jungle_strike.png",
    releaseDate: "2025-09-05",
    rating: 4.5,
    totalRatings: 820,
    totalPlays: 3100,
    isNewArrival: false,
    isTopRated: true,
    isMostPlayed: false,
    avgSessionDuration: 2,
    status: "active",
    createdAt: new Date().toISOString(),
  },
  {
    gameId: "game_005",
    gameName: "Arena Legends",
    platform: "PS5",
    genre: "Battle Arena",
    description: "Choose from 50 unique heroes and battle in spectacular arenas. Team-based combat with stunning visuals.",
    coverImageUrl: "/games/arena_legends.png",
    releaseDate: "2025-11-10",
    rating: 4.7,
    totalRatings: 1560,
    totalPlays: 6800,
    isNewArrival: false,
    isTopRated: true,
    isMostPlayed: true,
    avgSessionDuration: 2,
    status: "active",
    createdAt: new Date().toISOString(),
  },
  {
    gameId: "game_006",
    gameName: "Cyber Heist",
    platform: "Xbox Series X",
    genre: "Stealth Action",
    description: "Hack, infiltrate and steal in a neon-lit cyberpunk megacity. Plan the perfect heist across 15 high-stakes missions.",
    coverImageUrl: "/games/cyber_heist.png",
    releaseDate: "2026-02-14",
    rating: 4.4,
    totalRatings: 490,
    totalPlays: 2400,
    isNewArrival: true,
    isTopRated: false,
    isMostPlayed: false,
    avgSessionDuration: 2,
    status: "active",
    createdAt: new Date().toISOString(),
  },
];
